# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "server2016-core"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  # windows installs updates during startup and shutdown
  # larger timeouts hopefully prevents bricking the vm
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  # port forward WinRM and RDP
#  config.vm.network :forwarded_port, guest: 3389, host: 3389
#  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  # optional

  # config.winrm.username = "vagrant"
  # config.winrm.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
  #   # vb.gui = true
  #   vb.memory = "2048"
  #   vb.cpus = 2
     vb.name = "Windows_2016-core"
   end

end
